# share page on local network
host: 0.0.0.0 
port: 4000
url: "http://0.0.0.0" # the base hostname & protocol for your site, e.g. http://example.com
assets:
  compression: false
  gzip: false
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
    img: { integrity: false } # true on JEKYLL_ENV=production
  compress:
    css: false
    js: false