# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Beam Community
description: >- # this means to ignore newlines until "baseurl:"
  Dedicated to supporting, and growing, community packages and documentation for Elixir and Erlang.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://beam-community.org" # the base hostname & protocol for your site, e.g. http://example.com
analytics-id: 
# Social settings
github: beam-community

# seo-tag settings
# webmaster_verifications:
#   google: 
# twitter:
#   username: beamcommunity
#   card: summary

# Build settings
plugins:
  - jekyll-assets
  - kramdown
  - uglifier
  - jekyll-seo-tag

source: src
destination: www
markdown: kramdown

compress_html:
  ignore:
    envs: ["development"]
  clippings: []
  comments: all
  endings: []
  startings: []
  blanklines: false
  profile: false

assets:
  sources:
  - _assets/vendor
  digest: true
  compression: true
  gzip: true
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
    img: { integrity: false } # true on JEKYLL_ENV=production
  compress:
    css: true
    js: uglifier

include:
  - CNAME